$data=new customers_logs();
                $data->cust_id = $data['cust_id'];
                $data->cust_title = $request->input("cust_title");
                $data->cust_fname = $request->input('cust_fname');
                $data->cust_mname = $request->input('cust_mname');
                $data->cust_lname = $request->input('cust_lname');
                $data->gardian_title = $request->input('gardian_title');
                $data->gardian_fname = $request->input('gardian_fname');
                $data->gardian_mname = $request->input('gardian_mname');
                $data->gardian_lname = $request->input('gardian_lname');               
                $data->cust_email_address = $request->input('cust_email_address');
                $data->cust_gender = $request->input('cust_gender');
                $data->cust_date_of_birth = $request->input('cust_date_of_birth');
                $data->cust_mobile = $request->input('cust_mobile');
                $data->cust_profile_pic = "profile pic";
                $data->cust_signature_pic = "signature";
                $data->cust_aadharno = $request->input('cust_aadharno');
                $data->cust_document_aadhar = "Aadhar";
                $data->cust_document_pan = "pan";
                $data->cust_document_bankdt = "bank doc";
                $data->cust_panno = $request->input('cust_panno');                  
                $data->current_address_detail = $request->input('current_address_detail');
                $data->current_address_city = $request->input('current_address_city');
                $data->current_address_pincode = $request->input('current_address_pincode');
                $data->permanent_address_detail = $request->input('permanent_address_detail');
                $data->permanent_address_city = $request->input('permanent_address_city');
                $data->permanent_address_pincode = $request->input('permanent_address_pincode');
                $data->cust_account_number = $request->input('cust_account_number');
                $data->cust_bank_holder_name = $request->input('cust_bank_holder_name');
                $data->cust_bank_ifsc_code = $request->input('cust_bank_ifsc_code');
                $data->cust_bank_branch_code = $request->input('cust_bank_branch_code');
                $data->cust_bank_branche_name = $request->input('cust_bank_branche_name');
                $data->cust_bank_address = $request->input('cust_bank_address');
                // $data->cust_id ="CUST".date('Y').rand(00000,99999);
                // $data->cust_id = $request->$data['cust_id'];
                $data->cust_status = "Active";
            
            $data->save();
           
            dd($data);